experiment_name: "rag_generator_gpt2"

model:
  name: "gpt2-medium"
  max_length: 1024

paths:
  train_data: "data/processed/rag_dataset_train.jsonl"
  val_data: "data/processed/rag_dataset_val.jsonl"
  output_dir: "outputs/rag_checkpoints"

training:
  batch_size: 12
  epochs: 2
  lr: 0.0002
  warmup_steps: 100
  device: "cuda"

generation:
  max_new_tokens: 220

lora:
  r: 8
  alpha: 32
  dropout: 0.05
  target_modules: ["c_attn"]